# See the docs at https://github.com/geocoder-php/BazingaGeocoderBundle
bazinga_geocoder:
  providers:
    acme:
      factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
      options:
        region: 'fr'
        api_key: '%env(string:GEOCODING_GOOGLE_MAPS_API_KEY)%'