doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver: 'pdo_mysql'
    server_version: '5.7'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    mapping_types:
      enum: string
    types:
      bigint: App\DoctrineTypes\BigIntType
      enumTypeType: App\DoctrineTypes\Pricing\EnumTypeType
      enumTypeProvider: App\DoctrineTypes\Contract\EnumTypeProvider
      enumTypeDeliveryPointInvoiceType: App\DoctrineTypes\DeliveryPointInvoice\EnumTypeDeliveryPointInvoiceType
      enumTypeInvoiceTaxType: App\DoctrineTypes\InvoiceTax\EnumTypeInvoiceTaxType
      enumTypeAnalysisStatus: App\DoctrineTypes\Invoice\Analysis\EnumTypeAnalysisStatus
      enumTypeAnomalyStatus: App\DoctrineTypes\Invoice\Anomaly\EnumTypeAnomalyStatus
      enumTypeAnomalyType: App\DoctrineTypes\Invoice\Anomaly\EnumTypeAnomalyType
      enumInvoicePeriod: App\DoctrineTypes\Contract\EnumTypeInvoicePeriod
      enumTypeImportReportStatus: App\DoctrineTypes\ImportReport\EnumTypeImportReportStatus
      enumTypeImportType: App\DoctrineTypes\Import\EnumTypeImportType
      enumTypeDeliveryPointCreationMode: App\DoctrineTypes\DeliveryPoint\EnumTypeDeliveryPointCreationMode
      enumTypePermissionCode: App\DoctrineTypes\Permission\EnumTypePermissionCode
      enumTypeLanguage: App\DoctrineTypes\User\EnumTypeLanguage
      enumAnomalyProfit: App\DoctrineTypes\Invoice\Anomaly\EnumAnomalyProfit
      
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      gedmo_loggable:
        type: annotation
        prefix: Gedmo\Loggable\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
        alias: GedmoLoggable
        is_bundle: false
      gedmo_translatable:
        type: annotation
        prefix: Gedmo\Translatable\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
        alias: GedmoTranslatable
        is_bundle: false
