# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
  storages:
    s3.storage:
      adapter: 'aws'
      options:
        client: 'aws.s3' # The service ID of the Aws\S3\S3Client instance
        bucket: '%env(string:AWS_BUCKET)%'
    default.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/var/storage/default'
