api_login_check:
  path: /login

gesdinet_jwt_refresh_token:
  path: /token/refresh
  methods: POST
  controller: gesdinet.jwtrefreshtoken::refresh

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }