services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # Unit test
    App\Tests\Logger\Profiler\Db:
        arguments: ['@doctrine.dbal.logger.profiling.default']