services:
  Bazinga\GeocoderBundle\Mapping\Driver\AnnotationDriver:
    class: Bazinga\GeocoderBundle\Mapping\Driver\AnnotationDriver
    arguments:
      - '@annotations.reader'

  Bazinga\GeocoderBundle\Doctrine\ORM\GeocoderListener:
    class: Bazinga\GeocoderBundle\Doctrine\ORM\GeocoderListener
    arguments:
      - '@bazinga_geocoder.provider.acme'
      - '@Bazinga\GeocoderBundle\Mapping\Driver\AnnotationDriver'
    tags:
      - doctrine.event_subscriber